### PR TITLE
Command mappings for different Aquos models

### PR DESCRIPTION
**Pull request by HerrHofrat**
I came to this project over home assistant and had the problem that not all commands worked on my Europe Sharp Aquos LC70LE835E because the original source code was written for US models.
After having a look on the offical Sharp Aquos Android Remote App (http://upkeep.sharp.eu/cps/rde/xchg/eu/hs.xsl/-/html/aquos-remote-lite.htm) I refactored the original source code to look up commands in a yaml file. Based on the app, I created mappings for US, Europe, China and Japan.
It would be nice if someone could test at least the US version.

A further approach would be to define custom mapping files - probably I'll do that in an upcoming version - if necessary.

**Please be aware - I'm pretty new to python, normally I just code in Java/C++ - please let me know if I did anything completely wrong or in a bad python style!**

### CODE REVIEW

**Comment by HerrHofrat** [comment]
@jmoore987 I just wanted to ask if you already had some time to look at the PR and probably test it on your TV?

**Comment by jmoore987** [comment]
I missed the original notification.  I'll test your changes in the next day or two and merge the PR assuming everything is okay.

**Comment by jmoore987** [comment]
I got to test this a bit.  Can you change your code to make US the default, so as not to break backward compatibility?  There are several projects that depend on this package, so I like to stay as compatible as possible.

**Comment by HerrHofrat** [comment]
Sure! I've set the new parameter to the last position and set 'us' as default.

**Pull request merged**
