### PR TITLE
Fix 0.3.x release

### PR DESCRIPTION
**Pull request by titilambert**
Hello @jmoore987 you just forgot to update `setup.py` file.
So I got an issue to get the new version from pypi
This patch fixed it and create a new release: 0.3.1

### CODE REVIEW

**Comment by titilambert** [comment]
And I just added a missing "break"

**Comment by titilambert** [comment]
I also made more tests and sometimesI got some `socket.error` exception during the `sock_conn.recv` ...
So I improved the `_send_command` stability,

**Comment by jmoore987** [comment]
Hi @titilambert,
  Thanks for the fixes.  I've cut a new release implementing your pull request and pushed 0.3.1 to pypi.  

```
Jeffs-MacBook-Pro-2:sharp_aquos_rc jmoore$ pip --no-cache-dir search sharp_aquos_rc
sharp_aquos_rc (0.3.1)  - Control Sharp Aquos SmartTVs through the IP interface.
Jeffs-MacBook-Pro-2:sharp_aquos_rc jmoore$
```

https://pypi.python.org/pypi?:action=display&name=sharp_aquos_rc&version=0.3.1

Thanks for your patience.

Cheers,
Jeff

**Comment by titilambert** [comment]
Thanks !

**Pull request merged**
