### PR TITLE
Add remote control buttons, timeout, retries and pylint

### PR DESCRIPTION
**Pull request by titilambert**
Hello !

In order to improve Home-Assistant integration I got @adreznec commits and I added retries and pylint.
I really hope you will accept this PR and create a new release then I could improve the Home-Assistant component (https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/media_player/aquostv.py).

Tell me if you want I change something.

Thanks !

### CODE REVIEW

**Comment by jmoore987** [comment]
PR looks good.  Merged.  I'll cut a new release this weekend when I get a moment.

Thanks!

**Comment by titilambert** [comment]
@jmoore987 thanks for merging! and thanks for the release ! Could write here a message when you release it on pypi, then I will push the new version of the Home Assistant component.

Thanks !

**Comment by jmoore987** [comment]
@titilambert Your Pull requests should be reflected in v0.3 now on pypi.  

https://pypi.python.org/pypi/sharp_aquos_rc/0.3

Hope this works for you guys!

**Comment by titilambert** [comment]
Hello !
I can not get it from pypi
```
$ pip install sharp_aquos_rc==0.3
Collecting sharp_aquos_rc==0.3
  Could not find a version that satisfies the requirement sharp_aquos_rc==0.3 (from versions: 0.2)
No matching distribution found for sharp_aquos_rc==0.3
```
Do I need to wait for something ?

**Pull request merged**
